### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by Metaverse-Nabeel** [smunoz1988/JS-CapstoneProject#32]
Your project is complete! You have done it exceptionally well. But we found a few things missing; if you add those, your app would be much better.

@Metaverse-Nabeel

- There are multiple `console.log` statements in your code. I would recommend removing those.
- It is not good practice to use `/* eslint-enable */` for correcting linter errors. I would recommend removing those.
- `Readme` file is not ready. Don't forget to update professionally before submission for final review. 

@danielamoreno699

- All the functions and API calls are from `index.js`. I would recommend using separate modules for each task. As it is one of the objectives of this capstone project as well.
- I Will suggest making a separate function for the post comment, so you can call the post comment inside the submit function. Also, you can wrap the whole submit function since is not contained in a function.

**Comment by smunoz1988** [comment]
Thanks for the review. 

- The eslint enable is used because of the async function. 
- The Readme will be updated before sending the final review. 
- Great idea on the modules! we will definitively use them!
